### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by TheoXD** [LucCADORET/comeover#7]
Was the intention to release the project as open source? If it was, it should state under which license it was released. The project looks interesting, shouldn't be too far away from becoming fully decentralized and viable.

**Comment by LucCADORET** [comment]
It is my intention yeah. Thanks for reminding me I should take care of this. I also do think that with a little bit of polish it could become much more viable, unfortunately I don't have much time for this now. I should mostly make more docs in order to allow some motivated people to participate more easily.
